
eureka:
  client:
    # Server doesnot required to register it self hence set to false
    registerWithEureka: true
    # Server Does not required to fetch the registry it self
    fetchRegistry: true
    serviceUrl:
      # Server url is set to below
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
